"""
scout/cancellation.py — Cooperative cancellation for in-flight searches.

Provides a thread-safe registry of running searches keyed by request_id.
The scraper checks `is_cancelled(request_id)` at safe checkpoints and
raises SearchCancelledException to bail out cleanly.

Lifecycle:
    1. Router receives POST /search/products with a request_id from client
    2. Router calls register_search(request_id) → returns a threading.Event
    3. Router passes request_id to the scraper through the call chain
    4. Scraper checks is_cancelled(request_id) at expensive checkpoints
       (before Playwright, ScraperAPI, OpenAI calls, between platforms)
    5. If is_cancelled() returns True, raise SearchCancelledException
    6. Router catches the exception, returns a cancelled status to client
    7. Router calls cleanup_search(request_id) in finally block

Cancel endpoint:
    POST /search/cancel/{request_id} → cancel_search(request_id) sets the event

Why threading.Event (not asyncio.Event):
    The scraper runs in a ThreadPoolExecutor (see scrape_product_on_site).
    Playwright spawns its own event loop in its own thread. asyncio.Event
    only works within a single event loop. threading.Event is universally
    safe across threads, the asyncio loop, and Playwright's nested loop.
"""
import threading
from typing import Optional

# ── Registry ──────────────────────────────────────────────────────────
# Thread-safe dict of in-flight searches.
# Key: request_id (UUID generated by the frontend)
# Value: threading.Event — set() means cancellation requested.
_active_searches: dict[str, threading.Event] = {}
_lock = threading.Lock()


class SearchCancelledException(Exception):
    """Raised by scraper checkpoints when the user has cancelled."""
    pass


def register_search(request_id: str) -> threading.Event:
    """
    Create and register a new cancellation event for this request_id.
    Called at the start of /search/products.

    Returns the event so the caller can also pass it directly to
    long-running operations that accept an Event.
    """
    event = threading.Event()
    with _lock:
        _active_searches[request_id] = event
    return event


def is_cancelled(request_id: Optional[str]) -> bool:
    """
    Quick, lock-protected check used at scraper checkpoints.

    Returns False if request_id is None (no cancel context — e.g. internal
    monitor runs that don't go through the user-facing search flow).
    Returns False if the request_id was never registered (defensive).
    Returns True only if the event has been set() by cancel_search().
    """
    if not request_id:
        return False
    with _lock:
        event = _active_searches.get(request_id)
    return event.is_set() if event else False


def check_cancelled(request_id: Optional[str], where: str = "") -> None:
    """
    Convenience wrapper: raises SearchCancelledException if cancelled.
    Used at scraper checkpoints to bail out with one line:
        check_cancelled(request_id, "before Playwright on amazon.in")
    """
    if is_cancelled(request_id):
        raise SearchCancelledException(
            f"Search {request_id} cancelled by user" + (f" ({where})" if where else "")
        )


def cancel_search(request_id: str) -> bool:
    """
    Mark this search as cancelled.
    Called by the POST /search/cancel/{request_id} endpoint.

    Returns True if the request_id was found and cancelled.
    Returns False if no such search is in flight (already finished, or
    a stale ID from a closed browser tab).
    """
    with _lock:
        event = _active_searches.get(request_id)
    if event:
        event.set()
        return True
    return False


def cleanup_search(request_id: Optional[str]) -> None:
    """
    Remove the request_id from the registry.
    MUST be called in a finally block in the search handler so that even
    if the scrape raises an exception, we don't leak entries.
    Idempotent — safe to call even if request_id was never registered.
    """
    if not request_id:
        return
    with _lock:
        _active_searches.pop(request_id, None)


def active_count() -> int:
    """Diagnostic helper — returns number of currently in-flight searches."""
    with _lock:
        return len(_active_searches)