"""
scout/scout_db.py — PostgreSQL persistence layer for Scout Agent

Tables:
  websites         — tracked e-commerce sites (name, search_url, active)
  product_results  — most recent scrape result per product+platform
  price_history    — every price observation ever recorded
  price_alerts     — price change events generated by price monitor
  entities         — resolved product entities (cross-platform grouping)
  entity_listings  — one row per entity+platform with latest listing data
  product_features — cached feature extraction results (24h TTL)

Environment:
  DATABASE_URL  postgresql://user:pass@host:5433/dbname
  Default       postgresql://postgres:postgres@localhost:5433/scout
"""

from __future__ import annotations

import json
import logging
import os
from contextlib import contextmanager
from datetime import datetime, timezone
from typing import Any, Generator, Optional

import psycopg2
import psycopg2.extras

logger = logging.getLogger(__name__)

# ── Config ────────────────────────────────────────────────────────────
from dotenv import load_dotenv
load_dotenv()

_DATABASE_URL = os.environ.get("DATABASE_URL", "")


# ── Database class ────────────────────────────────────────────────────

class Database:
    """
    Thin wrapper around psycopg2.
    Every public method opens its own connection, commits on success,
    and rolls back on failure. Connections are never reused across calls.
    """

    def __init__(self) -> None:
        self._init_db()

    # ── Connection / cursor helpers ───────────────────────────────────

    @contextmanager
    def _conn(self) -> Generator:
        conn = psycopg2.connect(dsn=_DATABASE_URL)
        conn.autocommit = False
        try:
            yield conn
            conn.commit()
        except Exception:
            conn.rollback()
            raise
        finally:
            conn.close()
    # Normalization rules:
#   - lowercase (case-insensitive grouping)
#   - collapse all whitespace runs to single space (no double-space dupes)
#   - strip leading/trailing whitespace
#
# We deliberately do NOT strip punctuation or trademark symbols here —
# those are meaningful for distinguishing "coach watch" from "coach watch ™"
# and the brand normalization belongs in entity_resolver, not here.
    @staticmethod
    def _normalize_name(name: Optional[str]) -> str:
        if not name:
            return ""
        import re as _re
        return _re.sub(r"\s+", " ", str(name).strip().lower())

    def _fetchall(self, conn, query: str, params: tuple = ()) -> list[dict]:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(query, params)
            return [dict(r) for r in cur.fetchall()]

    def _fetchone(self, conn, query: str, params: tuple = ()) -> Optional[dict]:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(query, params)
            row = cur.fetchone()
            return dict(row) if row else None

    def _execute(self, conn, query: str, params: tuple = ()) -> None:
        with conn.cursor() as cur:
            cur.execute(query, params)

    # ── Schema initialisation ─────────────────────────────────────────

    def _init_db(self) -> None:
        with self._conn() as conn:
            # Websites
            self._execute(conn, """
                CREATE TABLE IF NOT EXISTS websites (
                    id         SERIAL PRIMARY KEY,
                    name       TEXT UNIQUE NOT NULL,
                    base_url   TEXT NOT NULL DEFAULT '',
                    search_url TEXT NOT NULL DEFAULT '',
                    encoding   TEXT NOT NULL DEFAULT 'plus',
                    active     BOOLEAN NOT NULL DEFAULT TRUE,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
            """)

            # Latest scrape result per product+platform
            self._execute(conn, """
                CREATE TABLE IF NOT EXISTS product_results (
                    id              SERIAL PRIMARY KEY,
                    product_name    TEXT NOT NULL,
                    platform        TEXT NOT NULL,
                    product_url     TEXT,
                    price           FLOAT,
                    product_details JSONB,
                    scraped_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    UNIQUE (product_name, platform)
                )
            """)

            # Full price history
            self._execute(conn, """
                CREATE TABLE IF NOT EXISTS price_history (
                    id           SERIAL PRIMARY KEY,
                    product_name TEXT NOT NULL,
                    platform     TEXT NOT NULL,
                    price        NUMERIC(10,2) NOT NULL,
                    currency     TEXT NOT NULL DEFAULT 'INR',
                    url          TEXT,
                    scraped_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
            """)
            self._execute(conn, """
                CREATE INDEX IF NOT EXISTS idx_price_history_product_platform
                ON price_history (product_name, platform, scraped_at DESC)
            """)

            # Price change alerts
            self._execute(conn, """
                CREATE TABLE IF NOT EXISTS price_alerts (
                    id             SERIAL PRIMARY KEY,
                    product_name   TEXT NOT NULL,
                    platform       TEXT NOT NULL,
                    old_price      NUMERIC(10,2),
                    new_price      NUMERIC(10,2) NOT NULL,
                    change_amount  NUMERIC(10,2),
                    change_percent NUMERIC(6,2),
                    direction      TEXT NOT NULL,
                    url            TEXT,
                    detected_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    acknowledged   BOOLEAN NOT NULL DEFAULT FALSE
                )
            """)
            self._execute(conn, """
                CREATE INDEX IF NOT EXISTS idx_price_alerts_product_platform
                ON price_alerts (product_name, platform, detected_at DESC)
            """)

            # Entity resolution — canonical product groups
            self._execute(conn, """
                CREATE TABLE IF NOT EXISTS entities (
                    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                    canonical_name    TEXT NOT NULL,
                    canonical_brand   TEXT,
                    canonical_variant TEXT,
                    query             TEXT NOT NULL,
                    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
            """)
            self._execute(conn, """
                CREATE INDEX IF NOT EXISTS idx_entities_query
                ON entities (query)
            """)

            # One row per entity+platform
            self._execute(conn, """
                CREATE TABLE IF NOT EXISTS entity_listings (
                    id           SERIAL PRIMARY KEY,
                    entity_id    UUID NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
                    platform     TEXT NOT NULL,
                    product_url  TEXT NOT NULL,
                    title        TEXT NOT NULL,
                    price        NUMERIC(10,2),
                    currency     TEXT NOT NULL DEFAULT 'INR',
                    ingredients  TEXT,
                    manufacturer TEXT,
                    marketed_by  TEXT,
                    availability TEXT DEFAULT 'unknown',
                    last_seen    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    UNIQUE (entity_id, platform)
                )
            """)
            self._execute(conn, """
                CREATE INDEX IF NOT EXISTS idx_entity_listings_entity_id
                ON entity_listings (entity_id)
            """)

            # Cached feature extraction results
            self._execute(conn, """
                CREATE TABLE IF NOT EXISTS product_features (
                    id             SERIAL PRIMARY KEY,
                    product_name   TEXT NOT NULL,
                    platform       TEXT NOT NULL,
                    category       TEXT,
                    product_feats  JSONB,
                    platform_feats JSONB,
                    extracted_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    UNIQUE (product_name, platform)
                )
            """)

    # ── Websites ──────────────────────────────────────────────────────

    def get_active_websites(self) -> list[dict]:
        with self._conn() as conn:
            return self._fetchall(
                conn,
                "SELECT * FROM websites WHERE active = TRUE ORDER BY name",
            )

    def get_all_websites(self) -> list[dict]:
        with self._conn() as conn:
            return self._fetchall(conn, "SELECT * FROM websites ORDER BY name")

    def get_website_by_name(self, name: str) -> Optional[dict]:
        with self._conn() as conn:
            return self._fetchone(
                conn, "SELECT * FROM websites WHERE name = %s", (name,)
            )

    def add_website(
        self,
        name:       str,
        base_url:   str,
        search_url: str,
        encoding:   str = "plus",
    ) -> dict:
        with self._conn() as conn:
            self._execute(conn, """
                INSERT INTO websites (name, base_url, search_url, encoding, active, created_at)
                VALUES (%s, %s, %s, %s, TRUE, NOW())
            """, (name, base_url, search_url, encoding))
        return self.get_website_by_name(name)

    def update_website(
        self,
        name:       str,
        active:     bool,
        base_url:   Optional[str] = None,
        search_url: Optional[str] = None,
    ) -> Optional[dict]:
        site = self.get_website_by_name(name)
        if not site:
            return None
        b = base_url   if base_url   is not None else site["base_url"]
        s = search_url if search_url is not None else site["search_url"]
        with self._conn() as conn:
            self._execute(conn, """
                UPDATE websites SET base_url = %s, search_url = %s, active = %s
                WHERE name = %s
            """, (b, s, active, name))
        return self.get_website_by_name(name)

    def delete_website(self, name: str) -> dict:
        """
        Permanently delete a website and ALL associated data:
          - websites row
          - product_results for this platform
          - price_history for this platform
          - price_alerts for this platform
          - product_features for this platform
          - entity_listings for this platform
          - entities that are left with zero listings afterwards

        All deletes happen in a single transaction via _conn() —
        if any step fails, the whole thing rolls back.

        Returns a dict of row counts per table, for logging and UI feedback.
        Raises ValueError if the website doesn't exist.
        """
        if not self.get_website_by_name(name):
            raise ValueError(f"Website '{name}' not found")

        counts = {}
        with self._conn() as conn:
            with conn.cursor() as cur:
                # Children first, parent last.
                cur.execute(
                    "DELETE FROM entity_listings WHERE platform = %s", (name,)
                )
                counts["entity_listings"] = cur.rowcount

                # Clean up entities that now have zero listings on any platform
                cur.execute("""
                    DELETE FROM entities
                    WHERE id NOT IN (SELECT DISTINCT entity_id FROM entity_listings)
                """)
                counts["entities_orphaned"] = cur.rowcount

                cur.execute(
                    "DELETE FROM product_features WHERE platform = %s", (name,)
                )
                counts["product_features"] = cur.rowcount

                cur.execute(
                    "DELETE FROM price_alerts WHERE platform = %s", (name,)
                )
                counts["price_alerts"] = cur.rowcount

                cur.execute(
                    "DELETE FROM price_history WHERE platform = %s", (name,)
                )
                counts["price_history"] = cur.rowcount

                cur.execute(
                    "DELETE FROM product_results WHERE platform = %s", (name,)
                )
                counts["product_results"] = cur.rowcount

                cur.execute(
                    "DELETE FROM websites WHERE name = %s", (name,)
                )
                counts["websites"] = cur.rowcount

        logger.info(f"[db] Permanently deleted website '{name}': {counts}")
        return counts

    # ── Product results ───────────────────────────────────────────────

    def save_product_result(self, row: dict, platforms: list[str]) -> None:
        """
        Upsert each listing as a separate row in product_results.
        price is extracted from the normalised listing format:
          { "price": {"value": 999.0, "currency": "INR"}, ... }
        """
        with self._conn() as conn:
            for listing in row.get("listings", []):
                # Normalize before insert — this is the root of all downstream keys.
                # If we save "NIVEA lip balm" here but price_history saves "nivea lip balm",
                # they won't match on JOIN or WHERE and the monitor UI will show duplicates.
                product_name = self._normalize_name(row.get("name", ""))
                platform     = str(listing.get("platform", ""))

                product_url  = listing.get("url") or None
                if product_url:
                    product_url = str(product_url)

                price_data = listing.get("price", {})
                price: float = 0.0
                try:
                    price = float(
                        price_data.get("value", 0)
                        if isinstance(price_data, dict)
                        else price_data
                    )
                except (TypeError, ValueError):
                    price = 0.0

                # Everything except the index fields goes into product_details
                product_details = {
                    k: v for k, v in listing.items()
                    if k not in {"platform", "url", "price"}
                }
                # Save currency separately — price dict is stripped above but
                # we need currency for get_all_products/get_cached_listing
                if isinstance(price_data, dict) and price_data.get("currency"):
                    product_details["currency"] = price_data["currency"]

                self._execute(conn, """
                    INSERT INTO product_results
                        (product_name, platform, product_url, price, product_details, scraped_at)
                    VALUES (%s, %s, %s, %s, %s::jsonb, NOW())
                    ON CONFLICT (product_name, platform) DO UPDATE SET
                        product_url     = EXCLUDED.product_url,
                        price           = EXCLUDED.price,
                        product_details = EXCLUDED.product_details,
                        scraped_at      = NOW()
                """, (
                    product_name,
                    platform,
                    product_url,
                    price,
                    json.dumps(product_details, default=str),
                ))

    def get_all_products(
        self,
        limit:  int = 0,   # 0 = no limit (preserves existing callers)
        offset: int = 0,
        ) -> tuple[list[dict], list[str], int]:
        """
        All tracked products from DB, grouped by product name.
        Returns (products_list, sorted_platform_names, total_count).

        Pagination happens at PRODUCT level (not row level) so the UI page
        size matches what the user sees. total_count is the number of
        distinct products so the frontend can render "Showing X-Y of N".

        When limit=0, returns all products (backward-compatible for any
        caller that wants the full list — e.g. tools.py).
        """
        with self._conn() as conn:
            rows = self._fetchall(conn, """
                SELECT product_name, platform, price, product_url, product_details, scraped_at
                FROM product_results
                ORDER BY scraped_at DESC
            """)

        products:     dict[str, dict] = {}
        platform_set: set[str]        = set()

        for row in rows:
            name     = row["product_name"]
            platform = row["platform"]
            platform_set.add(platform)

            if name not in products:
                products[name] = {"name": name, "listings": []}

            details: dict[str, Any] = row.get("product_details") or {}
            if isinstance(details, str):
                try:
                    details = json.loads(details)
                except Exception:
                    details = {}

            products[name]["listings"].append({
                "platform": platform,
                "price": {
                    "value":    float(row["price"]) if row["price"] else 0,
                    "currency": details.get("price", {}).get("currency", None)
                                or details.get("currency", "INR"),
                    "raw":      details.get("price", {}).get("raw", None)
                                or (f"₹{row['price']}" if row["price"] else None),
                },
                "url": row.get("product_url", ""),
                **{k: v for k, v in details.items() if k != "price"},
            })

        all_products = list(products.values())
        # Products are already in insertion order, which matches SQL ORDER BY
        # scraped_at DESC on the first row that introduced each product name.
        # That gives us "most recently scraped first" at the product level —
        # a sensible default for "Tracked Products".
        total = len(all_products)

        if limit > 0:
            paged = all_products[offset : offset + limit]
        else:
            paged = all_products

        return paged, sorted(platform_set), total

    # ── Price history ─────────────────────────────────────────────────

    def save_price(
        self,
        product_name: str,
        platform:     str,
        price:        float,
        currency:     str = "INR",
        url:          str = "",
        ) -> Optional[dict]:
        """
        Save a price observation. Skips duplicates within the last hour.
        Detects and saves price change alerts automatically.
        """
        if price <= 0:
            return None

        # Normalize at the start — every downstream read (get_last_price)
        # and write (price_history INSERT, price_alerts INSERT via
        # _detect_price_change) uses this same canonical form, so lookups
        # always hit. Before this fix, a scrape with "NIVEA lip balm" would
        # miss the lowercase rows from previous scrapes and fire a spurious
        # "new" alert even though history existed.
        product_name = self._normalize_name(product_name)

        last = self.get_last_price(product_name, platform)

        # Skip if same price was recorded in the last hour (dedup)
        if last:
            last_price = float(last["price"])
            last_time  = last["scraped_at"]
            if last_time.tzinfo is None:
                last_time = last_time.replace(tzinfo=timezone.utc)
            minutes_since = (datetime.now(timezone.utc) - last_time).total_seconds() / 60
            if last_price == price and minutes_since < 60:
                return None

        with self._conn() as conn:
            self._execute(conn, """
                INSERT INTO price_history
                    (product_name, platform, price, currency, url, scraped_at)
                VALUES (%s, %s, %s, %s, %s, NOW())
            """, (product_name, platform, price, currency, url))

        return self._detect_price_change(product_name, platform, last, price, url)

    def get_last_price(self, product_name: str, platform: str) -> Optional[dict]:
        """Most recent price record for a product+platform pair."""
        # Defensive: callers that bypass save_price (e.g. direct lookups from
        # tools.py or ad-hoc scripts) shouldn't have to remember to normalize.
        # Normalizing here makes all reads safe regardless of caller discipline.
        product_name = self._normalize_name(product_name)
        with self._conn() as conn:
            return self._fetchone(conn, """
                SELECT price, currency, url, scraped_at
                FROM price_history
                WHERE product_name = %s AND platform = %s
                ORDER BY scraped_at DESC
                LIMIT 1
            """, (product_name, platform))

    def get_price_history(
        self,
        product_name: str,
        platform:     Optional[str] = None,
        limit:        int = 90,
    ) -> list[dict]:
        """
        Price history for a product.
        If platform given → single platform.
        Otherwise         → all platforms.
        """
        # Normalize for same reason as get_last_price — this is a public
        # lookup method and callers shouldn't need to pre-normalize.
        product_name = self._normalize_name(product_name)
        with self._conn() as conn:
            if platform:
                return self._fetchall(conn, """
                    SELECT platform, price, currency, url, scraped_at
                    FROM price_history
                    WHERE product_name = %s AND platform = %s
                    ORDER BY scraped_at DESC
                    LIMIT %s
                """, (product_name, platform, limit))
            else:
                return self._fetchall(conn, """
                    SELECT platform, price, currency, url, scraped_at
                    FROM price_history
                    WHERE product_name = %s
                    ORDER BY platform, scraped_at DESC
                    LIMIT %s
                """, (product_name, limit))

    def _detect_price_change(
        self,
        product_name: str,
        platform:     str,
        last:         Optional[dict],
        new_price:    float,
        url:          str,
    ) -> Optional[dict]:
        """
        Compare new price to last known price.
        Saves a price alert if the change exceeds the threshold.
        """
        CHANGE_THRESHOLD_PERCENT = 1.0

        if not last:
            return self._save_alert(
                product_name  = product_name,
                platform      = platform,
                old_price     = None,
                new_price     = new_price,
                change_amount = None,
                change_percent= None,
                direction     = "new",
                url           = url,
            )

        old_price = float(last["price"])

        if old_price <= 0 and new_price > 0:
            return self._save_alert(
                product_name  = product_name,
                platform      = platform,
                old_price     = old_price,
                new_price     = new_price,
                change_amount = new_price,
                change_percent= None,
                direction     = "available",
                url           = url,
            )

        if old_price > 0 and new_price <= 0:
            return self._save_alert(
                product_name  = product_name,
                platform      = platform,
                old_price     = old_price,
                new_price     = new_price,
                change_amount = -old_price,
                change_percent= None,
                direction     = "unavailable",
                url           = url,
            )

        change_amount  = round(new_price - old_price, 2)
        change_percent = round((change_amount / old_price) * 100, 2)

        if abs(change_percent) < CHANGE_THRESHOLD_PERCENT:
            return None

        return self._save_alert(
            product_name   = product_name,
            platform       = platform,
            old_price      = old_price,
            new_price      = new_price,
            change_amount  = change_amount,
            change_percent = change_percent,
            direction      = "up" if change_amount > 0 else "down",
            url            = url,
        )

    def _save_alert(
        self,
        product_name:   str,
        platform:       str,
        old_price:      Optional[float],
        new_price:      float,
        change_amount:  Optional[float],
        change_percent: Optional[float],
        direction:      str,
        url:            str,
    ) -> Optional[dict]:
        """Persist a price alert; deduplicates within a 5-minute window."""
        with self._conn() as conn:
            existing = self._fetchone(conn, """
                SELECT id FROM price_alerts
                WHERE product_name = %s AND platform = %s
                  AND new_price = %s AND direction = %s
                  AND detected_at > NOW() - INTERVAL '5 minutes'
            """, (product_name, platform, new_price, direction))
            if existing:
                return None

        with self._conn() as conn:
            self._execute(conn, """
                INSERT INTO price_alerts
                    (product_name, platform, old_price, new_price,
                     change_amount, change_percent, direction, url, detected_at)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, NOW())
            """, (
                product_name, platform, old_price, new_price,
                change_amount, change_percent, direction, url,
            ))

        print(
            f"  [price] 🔔 Alert: {product_name} on {platform} "
            f"{direction} {old_price} → {new_price} ({change_percent}%)"
        )
        return {
            "product_name":   product_name,
            "platform":       platform,
            "old_price":      old_price,
            "new_price":      new_price,
            "change_amount":  change_amount,
            "change_percent": change_percent,
            "direction":      direction,
            "url":            url,
        }

    # ── Price alerts ──────────────────────────────────────────────────

    def get_alerts(
        self,
        unacknowledged_only: bool = False,
        limit:               int  = 50,
        offset:              int  = 0,
    ) -> tuple[list[dict], int]:
        """
        Returns (rows, total_count).
        total_count is the full unpaged size — used by the frontend to render
        "Showing X-Y of N" and determine whether to enable the Next button.

        Each alert row now also includes 'title' — the actual scraped product
        title from the matching product_results row. Falls back to product_name
        (the user's search query) if no matching scrape result exists, so the
        UI never shows blank.
        """
        # The JOIN gets the scraped title from product_details JSON.
        # COALESCE falls back to product_name so the UI never shows blank
        # if the product_results row was deleted or has no title field.
        select_with_title = """
            SELECT
                a.*,
                COALESCE(
                    pr.product_details->>'title',
                    a.product_name
                ) AS title
            FROM price_alerts a
            LEFT JOIN product_results pr
              ON pr.product_name = a.product_name
             AND pr.platform     = a.platform
        """

        with self._conn() as conn:
            if unacknowledged_only:
                rows = self._fetchall(conn, f"""
                    {select_with_title}
                    WHERE a.acknowledged = FALSE
                    ORDER BY a.detected_at DESC
                    LIMIT %s OFFSET %s
                """, (limit, offset))
                total_row = self._fetchone(conn,
                    "SELECT COUNT(*) AS count FROM price_alerts WHERE acknowledged = FALSE")
            else:
                rows = self._fetchall(conn, f"""
                    {select_with_title}
                    ORDER BY a.detected_at DESC
                    LIMIT %s OFFSET %s
                """, (limit, offset))
                total_row = self._fetchone(conn,
                    "SELECT COUNT(*) AS count FROM price_alerts")

            total = int(total_row["count"]) if total_row else 0
            return rows, total

    def acknowledge_alert(self, alert_id: int) -> bool:
        with self._conn() as conn:
            with conn.cursor() as cur:
                cur.execute("""
                    UPDATE price_alerts SET acknowledged = TRUE WHERE id = %s
                """, (alert_id,))
                return cur.rowcount > 0

    def acknowledge_all_alerts(self) -> int:
        with self._conn() as conn:
            with conn.cursor() as cur:
                cur.execute("""
                    UPDATE price_alerts SET acknowledged = TRUE WHERE acknowledged = FALSE
                """)
                return cur.rowcount

    def get_unacknowledged_count(self) -> int:
        with self._conn() as conn:
            row = self._fetchone(
                conn,
                "SELECT COUNT(*) AS count FROM price_alerts WHERE acknowledged = FALSE",
            )
            return int(row["count"]) if row else 0

    # ── Cache helpers ─────────────────────────────────────────────────

    def get_cached_listing(
        self,
        product_name: str,
        platform:     str,
        ttl_minutes:  int = 120,
    ) -> Optional[dict]:
        """Return cached listing if scraped within ttl_minutes; else None."""
        product_name = self._normalize_name(product_name)
        with self._conn() as conn:
            row = self._fetchone(conn, """
                SELECT
                    product_name, platform, price, product_url,
                    product_details, scraped_at,
                    EXTRACT(EPOCH FROM (NOW() - scraped_at)) / 60 AS age_minutes
                FROM product_results
                WHERE product_name = %s
                  AND platform = %s
                  AND scraped_at > NOW() - (%s * INTERVAL '1 minute')
                ORDER BY scraped_at DESC
                LIMIT 1
            """, (product_name, platform, ttl_minutes))

        if not row:
            return None

        details: dict[str, Any] = row.get("product_details") or {}
        if isinstance(details, str):
            try:
                details = json.loads(details)
            except Exception:
                details = {}

        # Detect currency from stored product_details
        stored_currency = (
            details.get("price", {}).get("currency", None)
            if isinstance(details.get("price"), dict) else None
        ) or details.get("currency", "INR")

        return {
            "platform":     platform,
            "title":        product_name,
            "price": {
                "value":    float(row["price"]) if row["price"] else 0,
                "currency": stored_currency,
                "raw":      details.get("price", {}).get("raw", None)
                            if isinstance(details.get("price"), dict) else None,
            },
            "url":          row.get("product_url", ""),
            "availability": details.get("availability", "in_stock" if row["price"] else "unknown"),
            "manufacturer": details.get("manufacturer", ""),
            "marketed_by":  details.get("marketed_by", ""),
            "age_minutes":  round(float(row["age_minutes"]), 1),
            "source":       "cache",
            **{
                k: v for k, v in details.items()
                if k not in {"availability", "manufacturer", "marketed_by", "platform", "url", "price"}
            },
        }

    def get_listing_age_minutes(
        self, product_name: str, platform: str
    ) -> Optional[float]:
        """How many minutes ago was this product last scraped? None if never."""
        product_name = self._normalize_name(product_name)
        with self._conn() as conn:
            row = self._fetchone(conn, """
                SELECT EXTRACT(EPOCH FROM (NOW() - scraped_at)) / 60 AS age_minutes
                FROM product_results
                WHERE product_name = %s AND platform = %s
                ORDER BY scraped_at DESC
                LIMIT 1
            """, (product_name, platform))
        return round(float(row["age_minutes"]), 1) if row else None

    # ── Feature cache ─────────────────────────────────────────────────

    def get_cached_features(
        self,
        product_name: str,
        platform:     str,
        ttl_minutes:  int = 1440,   # 24 hours
    ) -> Optional[dict]:
        product_name = self._normalize_name(product_name)
        with self._conn() as conn:
            row = self._fetchone(conn, """
                SELECT product_feats, platform_feats, category, extracted_at
                FROM product_features
                WHERE product_name = %s AND platform = %s
                  AND extracted_at > NOW() - (%s * INTERVAL '1 minute')
                ORDER BY extracted_at DESC LIMIT 1
            """, (product_name, platform, ttl_minutes))
        return row  # None if not found or expired

    def save_features(
        self,
        product_name:   str,
        platform:       str,
        category:       str,
        product_feats:  dict,
        platform_feats: dict,
    ) -> None:
        product_name = self._normalize_name(product_name)
        with self._conn() as conn:
            self._execute(conn, """
                INSERT INTO product_features
                    (product_name, platform, category,
                     product_feats, platform_feats, extracted_at)
                VALUES (%s, %s, %s, %s::jsonb, %s::jsonb, NOW())
                ON CONFLICT (product_name, platform) DO UPDATE SET
                    category       = EXCLUDED.category,
                    product_feats  = EXCLUDED.product_feats,
                    platform_feats = EXCLUDED.platform_feats,
                    extracted_at   = NOW()
            """, (
                product_name, platform, category,
                json.dumps(product_feats),
                json.dumps(platform_feats),
            ))

    def link_product_to_entity(self, product_name: str, entity_id: str):
        """
        After entity resolution, link the client's product record 
        to the Scout entity so the strategist can JOIN them.
        
        NOTE: This targets `public.products` which is an EXTERNAL table
        (e.g., from a client's system). If the table doesn't exist in this
        database, the update is silently skipped.
        """
        try:
            with self._conn() as conn:
                # Check if the table exists first
                exists = self._fetchone(conn, """
                    SELECT 1 FROM information_schema.tables
                    WHERE table_schema = 'public' AND table_name = 'products'
                """)
                if not exists:
                    return  # Table doesn't exist — nothing to link

                self._execute(conn, """
                    UPDATE public.products
                    SET scout_entity_id = %s
                    WHERE LOWER(product_name) = LOWER(%s)
                    AND scout_entity_id IS NULL
                """, (entity_id, product_name))
        except Exception as e:
            # Don't let a missing external table crash the main flow
            logger.debug(f"[db] link_product_to_entity skipped: {e}")
# ── Module-level singleton ─────────────────────────────────────────────
db = Database()